workspace:
  base: /go
  path: src/github.com/drone/drone-volume-cache

pipeline:
  build:
    image: golang:1.8
    commands: sh .drone.sh

  publish_linux_amd64:
    image: plugins/docker
    repo: plugins/volume-cache
    tags: [ latest, 1.0.0, 1.0, 1 ]
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

  publish_linux_arm64:
    image: plugins/docker
    repo: plugins/volume-cache
    tags: [ linux-arm64 ]
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile.arm64
    when:
      branch: master
      event: push

  publish_linux_arm:
    image: plugins/docker
    repo: plugins/volume-cache
    tags: [ linux-arm ]
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile.arm
    when:
      branch: master
      event: push
