[[constraint]]
  branch = "master"
  name = "github.com/drone/drone-cache-lib"

[[constraint]]
  name = "github.com/replicon/fast-archiver"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true
